<?php

declare(strict_types=1);

namespace App\Billing\Export\Manifests;

use App\Billing\Export\Contracts\ExportDataset;
use App\Billing\Export\Contracts\LoadManifestGenerator;
use App\Billing\Export\ValueObjects\ExportColumn;
use App\Billing\Export\ValueObjects\WrittenPartition;

/**
 * Shared rendering for the per-warehouse load-manifest generators — the column DDL and the
 * staged-location resolution every dialect needs. The actual `COPY`/`bq load`/DDL text lives in
 * the concrete generators, because each warehouse's load grammar is genuinely different; this
 * base only removes the mechanical repetition, never papers over a dialect difference.
 */
abstract class AbstractManifest implements LoadManifestGenerator
{
    /**
     * Render the column list as `name TYPE` lines for a CREATE TABLE, using the per-warehouse
     * physical type of each column.
     *
     * @param  list<ExportColumn>  $schema
     * @param  callable(ExportColumn): string  $type
     */
    protected function columnDdl(array $schema, callable $type, string $indent = '    '): string
    {
        $lines = array_map(
            static fn (ExportColumn $c): string => $indent.$c->name.' '.$type($c),
            $schema,
        );

        return implode(",\n", $lines);
    }

    /**
     * The comma-separated column-name list (for INSERT/SELECT column projections).
     *
     * @param  list<ExportColumn>  $schema
     */
    protected function columnNames(array $schema): string
    {
        return implode(', ', array_map(static fn (ExportColumn $c): string => $c->name, $schema));
    }

    /**
     * The MERGE match predicate joining a target `t` and staged `s` on the dataset's natural key.
     */
    protected function keyMatch(ExportDataset $dataset, string $target = 't', string $stage = 's'): string
    {
        $keys = $dataset->mergeKeys();

        if ($keys === []) {
            $keys = ['id'];
        }

        $predicates = array_map(
            static fn (string $k): string => "{$target}.{$k} = {$stage}.{$k}",
            $keys,
        );

        return implode(' AND ', $predicates);
    }

    /** The header comment every generated manifest opens with. */
    protected function banner(string $warehouse, ExportDataset $dataset, WrittenPartition $partition): string
    {
        return sprintf(
            "-- %s load manifest — dataset `%s` (%s load)\n".
            "-- Generated by Cbox Billing for staged partition: %s\n".
            "-- Rows: %d · Bytes: %d · Plane: %s · Partition date: %s\n".
            '-- Replace any <bracketed> placeholder with your load-side value before running.',
            $warehouse,
            $dataset->key(),
            $partition->syncMode->value,
            $partition->path,
            $partition->rows,
            $partition->bytes,
            $partition->livemode ? 'live' : 'test',
            $partition->partitionDate,
        );
    }
}
